version: '3.8'

services:
  # PostgreSQL база данных
  db:
    image: postgres:13
    container_name: iset-katalog-db
    restart: always
    environment:
      POSTGRES_DB: connector_catalog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aboba1337
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../database/schema:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d connector_catalog"]
      interval: 10s
      timeout: 5s
      retries: 5

  # API сервер
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: iset-katalog-api
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: connector_catalog
      DB_USER: postgres
      DB_PASSWORD: aboba1337
    ports:
      - "8000:8000"
    volumes:
      - ../database/Zapchasti:/app/database/Zapchasti

# Именованный том для сохранения данных PostgreSQL
volumes:
  postgres_data:
    name: iset-katalog-postgres-data 